### ISSUE TITLE
Externalize Constants to JSON

### ISSUE THREAD

**Issue by Timer** [powerbot/RSBot-API#1114]
To deliver more timely updates.

**Comment by iitc** [comment]
You should make a nice little rest api for these types of things.. ;)

**Comment by Strikegently** [comment]
Reopening this. This will reduce client downtime by allowing us to update over the air.

**Comment by Paris** [comment]
Just to add some notes here, the release is bundled with all its Maven dependencies and minified with ProGuard to remove unused classes before being finally obfuscated. This means we can add external packages for JSON.

I'm hoping to release v8.1 before the end of this month which will be fully Java 11. I haven't checked if JDK 11 has its own JSON package, either way you're welcome to work on this change on a branch and I'll merge it in and tidy it up for v8.1.

The only downside to using externalised constants is that it's easy to make mistakes in the string names which will cause breakages. For this reason I suggest we use a `.properties` file in `src/main/resources` so IntelliJ can intelligently scan those keys and highlight misspellings or nonexistent constants in the code. Even though this will bundle a version of that file in the bot release I'll add some code to the network side to make it pull and override a newer version on the server.

**Comment by Strikegently** [comment]
I did consider using a properties file, but I went with JSON since it allows for more structure.
I'm also reorganizing the Constants file so it is easier to find relevant information; the JSON file matches this structure. 

My goal here is to load the constants file remotely - not from a bundled file. Widgets change all the time and right now it requires we make a dedicated release to fix it. If we instead load the JSON file from a network resource, then we can just update this and there's no need to make a dedicated release. We could even load it directly from Github so as soon as a PR is merged into master it's fixed. 

I have set up to use reflection, so there is a very small amount of code to maintain. I pushed my branch so you can see what I'm talking about.
Loader: https://github.com/dequeue/RSBot/blob/external-constants/src/main/java/org/powerbot/bot/ConstantsLoader.java
Example of constants: https://github.com/powerbot/RSBot-API/commit/0ec3277b114ec131e3aaef80097135e36fb8d0b8

**Comment by Strikegently** [comment]
alright i threw out my solution. It was excessively complicated.

**Comment by Paris** [comment]
Since github.com rate limits requests we'll mirror this on our own server and CDNs on the live release.
