### ISSUE TITLE
Bypass two client limit

### ISSUE THREAD

**Issue by AshGreh** [powerbot/RSBot-API#1736]
A good portion of the users would prefer to open more than two clients without the advertisements error whilst also avoiding spam clicking New Bot option. 
Two possible ways to solve this would be to either:
Give an option to bulk launch clients.
Figure out the internal limitation enforced and bypass it.

**Comment by ChrisBPB** [comment]
limitation is cache related IIRC

An idea would be to do what other clients are doing now are instead of limiting the client to the RS client, (optionally) allow it to attach to OSBuddy. This would be a great idea because 1) people love osbuddy, 2) osbuddy has useful features such as screenshots on levels, and display info (which could be used alongside 'afk' scripts to keep an eye on things without needing to check you have enough runes or potions or whatever you are doing (splashing nmz etc) 3) osbuddy creates its own jagexcache which is why it allows itself to bypass the 2 client restriction


osbuddy is osrs only though ofcourse

**Comment by ChrisBPB** [comment]
Possible solution would be to set the '-Duser.home=' on launch, - i.e -Duser.home=C:\Chris\caches\totallynotpowerbot{x} then increment x on each launch. However I believe this would not work properly on first launch as it has to build the cache and reload before it will fully function?

also I imagine creating a directory for powerbot to use as a cache would be an immediate giveaway if they just checked the cache directory

**Comment by benpoulson** [comment]
Is this issue still around? I'm able to open up 4 clients without issue.

https://imgur.com/a/KE1bScq

**Comment by ChrisBPB** [comment]
I'm running Mojave and I actually can't open 2 clients, if I try to open a second it just brings the one that is already opened to the front and gives it focus. Also when I close the client I get a message that the jar could not be opened (this comes up regardless of if I attempt to open a second or not)

I do not have a windows machine currently, or parallels/bootcamp set up, to test that

**Comment by AshGreh** [comment]
That issue is still around, you might have spam clicked. Chris's theory does work though. I wrote a launcher for that and it was working really well. The only question we need to answer for this is, where do we store the caches. Do we allow the user to decide it? Or do we do <defaultjagexcachepath>/<randomfoldername>?

**Comment by Paris** [comment]
I'm reluctant to support this at least until multiple script licenses are supported. It could also result in ban rates or system crashes.
