### ISSUE TITLE
Equipment Not Updating

### ISSUE THREAD

**Issue by iDznPB** [powerbot/RSBot-API#2080]
ctx.equipment.itemAt(Equipment.Slot.MAIN_HAND).id()

As an example doesn't update until the equipment tab is open. From my understanding, this should only be the case for quiver and ring as they're not 'visible'.

https://gyazo.com/26363bd154816fe6cfda5779108577cc

**Comment by tanlines** [comment]
I have experienced this as well.

**Comment by iDznPB** [comment]
I believe this has been fixed in the new release of 7114.

**Comment by iDznPB** [comment]
Sorry ignore this.

**Comment by iDznPB** [comment]
This is definitely not fixed.

I cleared my cache, and it worked, then as soon as I opened the equipment tab, it no longer works till I clear my cache again.

**Comment by benpoulson** [comment]
Looking through the source at https://github.com/powerbot/powerbot/blob/54c454be0363f800987d14411b36174c4c21d7d6/src/main/java/org/powerbot/script/rt4/Equipment.java#L46 it would seem that the itemAt method only works when the equipment tab is open, as it's looking at the widget values not the player appearance.

I see why this was done this way.. because as you said, player appearance doesn't show quiver or rings.

What would you want the preferred solution to be in this instance?
Our options are:
* You use ctx.players.local().appearance()
* Some form of hack where the equipment menu is opened whenever you call itemAt() 🤢 
* A mixup of the two, and use appearance when available, and fall back to the above hack for rings and quiver.

**Comment by iDznPB** [comment]
The annoying thing is it never used to be like that, But if it’s changed and can’t go back then yeah a mix up of the two as that’s what I’ve had to default to anyway.

**Comment by Strikegently** [comment]
Option 3 is what I feel would be the best. For rings or quiver, use widgets. Otherwise use appearance.

**Comment by Strikegently** [comment]
So basically what I suggested is what's being done already. 
If the equipment widget is visible, use the values there. Otherwise, fall back to appearance. 
I tested with every equipment slot and it worked as it should. 
```
final boolean v = c.visible();
...
return new Item(ctx, c, v ? c.itemId() : data[index], v ? c.itemStackSize() : 1);
```

https://github.com/powerbot/RSBot-API/blob/54c454be0363f800987d14411b36174c4c21d7d6/src/main/java/org/powerbot/script/rt4/Equipment.java#L51
