### ISSUE TITLE
Withdraw quantity broken

### ISSUE THREAD

**Issue by RZME** [powerbot/RSBot-API#2092]
Need for revision for the `withdrawModeQuantity` method.

Varpbits change across instances:
![](https://i.gyazo.com/959dea99123bf41e027840607d708111.png)

I wrote my own method and found these 4 different values: I check the current value of the varp to determine which constant to use, i.e. value > 1000.

This is the one of the cases I found but there are probably more.
The second one is regarding the `varpbit` for getting a kill in the revenant cave.
When running 2 instances it updates on 1, when running just 1 it doesn't (Sometimes it does but 7/10 times not)

```public enum BANK{
        ALL(16), ONE(0), ALL2(18808849), ONE2(18808833);

        private int numVal;

        BANK(int numVal) {
            this.numVal = numVal;
        }

        public int VALUE() {
            return numVal;
        }
    }

**Comment by benpoulson** [comment]
Have been able to replicate.

**Comment by AshGreh** [comment]
I have a solution. I'm looking for better alternatives at the moment.

**Comment by ArtificialPB** [comment]
Never compare the absolute value of a varbit. Each bit in the varpbit means a different thing and multiple, unrelated states can be in the same varbit under a different bit. That's why you're getting a different value.

When dealing with varbits, always shift and mask to get only the state you want.

**Comment by Strikegently** [comment]
Is this still an issue?
